### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dalb8** [gsingh93/hacker-live-wallpaper#1]
Just wondering if this is free to distribute: either way it would be a good idea to make the license more explicit. If it's free I'd like to distribute it via f-droid.org. BTW, one of the gitmodules has an ssh url.

**Comment by gsingh93** [comment]
FYI: the app has been updated, I don't know how updates work on fdroid.

**Comment by dalb8** [comment]
sorry, I no longer contribute to that. Do contact him to encourage him to update the app.

-------- Original Message --------
